### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by filippog** [albert-widi/twemproxy_exporter#1]
Hi @albert-widi !
I'd be interested in using twemproxy_exporter, I can't find a LICENSE file or sth similar. What license is it released under?

thanks!

**Comment by albertwidi** [comment]
@filippog sorry for my very late response. Been not active for a while and not see this message. I will add a License to this, this software is actually free to use and I will put it under MIT License

**Comment by filippog** [comment]
@albert-widi no problem! thanks a lot
